---
title: "Abundance Analysis"
output: html_document
date: "2023-12-12"
---

# Goal
Compare abundance of cells of each type between usp and control condition

```{r}
library(DESeq2)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggsignif)
```

```{r}
usp_ctrl_combined_annotated <- readRDS(file="/g/huber/users/lazoriak/usp_ctrl_combined_annotated.rds")
```

```{r}
usp_ctrl_combined_annotated$celltype_manual <- case_when (
  usp_ctrl_combined_annotated$celltype_manual %in% c("aEC", "pEC", "LFC") ~ "EC",
  TRUE ~ as.character(usp_ctrl_combined_annotated$celltype_manual))

usp_ctrl_combined_annotated@meta.data$tmp_celltype <- case_when(
  # we are only interested in differentiated celltypes and progenitor cell types. No intermediate celltypes
  usp_ctrl_combined_annotated$celltype_manual %in% c("dEC", "MT", "unk") ~ NA_character_, 
  usp_ctrl_combined_annotated$celltype_manual %in% c("aEC", "pEC", "LFC") ~ "EC", 
  T ~ usp_ctrl_combined_annotated$celltype_manual
  )

usp_ctrl_combined_annotated@meta.data$orig.ident <- case_when(
  usp_ctrl_combined_annotated$orig.ident == "DS-00151" ~ "Control Replicate 1",
  usp_ctrl_combined_annotated$orig.ident == "DS-00184"~ "Control Replicate 2",
  usp_ctrl_combined_annotated$orig.ident == "DS-00157"~ "USP Replicate 1",
  usp_ctrl_combined_annotated$orig.ident == "DS-00185"~ "USP Replicate 2",
) %>% factor(., levels = c("Control Replicate 1", "Control Replicate 2",
                           "USP Replicate 1","USP Replicate 2"))

usp_ctrl_combined_annotated_subset <- usp_ctrl_combined_annotated[,!is.na(usp_ctrl_combined_annotated$tmp_celltype)]
```


```{r}
# creating "count table" for DESeq2

cnts <- usp_ctrl_combined_annotated_subset@meta.data %>% 
  group_by(orig.ident, celltype_manual) %>% 
  # this counts cells per celltype
  tally() %>% 
  pivot_wider(., names_from = "orig.ident",
              values_from = "n") %>% 
  column_to_rownames("celltype_manual") %>% 
  as.matrix()

# defining model matrix
exp_design <- usp_ctrl_combined_annotated_subset@meta.data[,c("orig.ident", "group_id")] %>%
  data.frame() %>%
  distinct()

exp_design$orig.ident <- factor(exp_design$orig.ident, levels=c("Control Replicate 1", "Control Replicate 2",
                           "USP Replicate 1","USP Replicate 2"))

rownames(exp_design) <- exp_design$orig.ident

model <- model.matrix(~ group_id, data = exp_design)


dds <- DESeqDataSetFromMatrix(countData = cnts,
                              colData = exp_design,
                              design = ~group_id)

sizeFactors(dds) = colSums(cnts)/mean(colSums(cnts))

# running DESeq2. 
result <- DESeq(dds, fitType='local') # only 4 "genes" so dont fit smooth trend line of dispersion ~ mean
out_deseq <- results(result) %>% 
  data.frame() %>% 
  arrange(padj)
out_deseq
```


```{r}
#####################
# VISUALIZING RESULTS #
#####################

plot_df  <- counts(dds, norm=T) %>% 
  data.frame() %>% 
  rownames_to_column("celltype_manual") %>% 
  pivot_longer(-celltype_manual,names_to = "replicate", values_to = "n_cells") %>% 
  mutate(celltype=factor(celltype_manual, levels=c("EE","EB","ISC","EC"))) %>% 
  mutate(replicate = str_replace_all(.$replicate,"\\."," ")) %>% 
  mutate(replicate=factor(replicate, levels=c("Control Replicate 1","Control Replicate 2","USP Replicate 1","USP Replicate 2"))) %>%
  mutate(Condition = ifelse(grepl("USP",replicate), "USP\nknockout","Control")) 
plot_df
```
```{r}
annotation_df <- data.frame(
  celltype = c("EE","EB","ISC","EC"),
  start = c("Control"), 
  end = c("USP\nknockout"),
  y = c(130, 3100, 800,3000),
  label = c("n.s.", "n.s.", "\n*", "n.s.")
)
annotation_df$celltype <- factor(annotation_df$celltype , levels=c("EE","EB","ISC","EC"))
```

```{r}
p <- ggplot(plot_df, aes(x=Condition, y=n_cells,color=replicate))+
  geom_point(size=1.5)+
  geom_blank(mapping=aes(x=Condition, y=n_cells,color=replicate)) +
  geom_signif(
    data = annotation_df,
    mapping=aes(xmin = start, xmax = end, annotations = label, y_position = y, tip_length=0),
    textsize = 4.3, vjust = 0.0, 
    manual = TRUE,
    inherit.aes = FALSE
  )+
  stat_summary(fun="mean", geom="crossbar",
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.2,
                 position=position_dodge(),show.legend = FALSE, color="red")+
  facet_wrap(~celltype, scales = "free_y", ncol = 4) + 
  ylab("Normalized\nnumber of cells")
p
```